apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fk33m7rsb-go 
  janus-idp.io/tekton: fk33m7rsb-go
  backstage.io/kubernetes-id: fk33m7rsb-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fk33m7rsb-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml