apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fk33m7rsb-go-gitops
  description: This is GitOps manifest for fk33m7rsb-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=fk33m7rsb-go
    backstage.io/kubernetes-id: fk33m7rsb-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: fk33m7rsb-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:fk33m7rsb-go
